# Generated by Django 2.0.3 on 2018-04-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0002_auto_20180401_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='slantapp.Publication'),
        ),
    ]
