# Generated by Django 2.0.3 on 2018-04-04 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0003_auto_20180401_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bias',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
