# Generated by Django 2.0.4 on 2018-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0005_article_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
