# Generated by Django 2.0.4 on 2018-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0006_issue_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
