# Generated by Django 2.0.4 on 2018-04-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0007_issue_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=250)),
                ('url_root', models.URLField(max_length=500)),
                ('url_full', models.URLField(max_length=500)),
                ('url_keys_include', models.TextField()),
                ('url_keys_exclude', models.TextField()),
            ],
        ),
    ]
