# Generated by Django 2.0.4 on 2018-04-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0008_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url_prepend',
            field=models.URLField(default='', max_length=500, null=True),
        ),
    ]
