# Generated by Django 2.0.4 on 2018-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0009_site_url_prepend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url_prepend',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
