# Generated by Django 2.0.4 on 2018-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0010_auto_20180426_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url_keys_include',
            field=models.TextField(blank=True),
        ),
    ]
