# Generated by Django 2.0.4 on 2018-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0011_auto_20180426_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_full',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_keys_exclude',
            field=models.TextField(default='somenonsensestring'),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_keys_include',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_prepend',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url_root',
            field=models.URLField(default='', max_length=500),
        ),
    ]
