# Generated by Django 2.0.4 on 2018-04-30 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0012_auto_20180427_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='scrape',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='bias',
            field=models.IntegerField(default=50, help_text='Select a number between 0 and 100, where 0 is extremely liberal, and 100 is extremely conservative.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url_keys_include',
            field=models.TextField(blank=True, help_text='Separate keywords with a comma, no space.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url_prepend',
            field=models.URLField(blank=True, default='', help_text='Add URL without trailing slash.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url_root',
            field=models.URLField(default='', help_text='Add URL without trailing slash.', max_length=500),
        ),
    ]
