# Generated by Django 2.0.4 on 2018-05-02 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0013_auto_20180429_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AddField(
            model_name='article',
            name='scrape_date',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1)),
        ),
    ]
