# Generated by Django 2.0.4 on 2018-05-02 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0014_auto_20180501_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='slantapp.Issue'),
        ),
    ]
