# Generated by Django 2.0.4 on 2018-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0016_auto_20180501_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
