# Generated by Django 2.0.4 on 2018-05-02 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0017_auto_20180502_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='scrape_date',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
