# Generated by Django 2.0.4 on 2018-05-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0018_auto_20180502_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
