# Generated by Django 2.0.4 on 2018-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0019_article_topic_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
