# Generated by Django 2.0.4 on 2018-05-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0021_auto_20180507_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url_blacklist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
