# Generated by Django 2.0.4 on 2018-05-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0022_publication_url_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='url_prepend',
            field=models.TextField(blank=True, default='', help_text='Add URL without trailing slash.', null=True),
        ),
    ]
