# Generated by Django 2.0.4 on 2018-05-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0023_auto_20180509_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='url_keys_exclude',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url_keys_include',
        ),
    ]
