# Generated by Django 2.0.4 on 2018-05-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0024_auto_20180510_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
