# Generated by Django 2.0.4 on 2018-05-31 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0027_issue_summary_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scrape_timestamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
