# Generated by Django 2.0.4 on 2018-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0028_article_scrape_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scrape_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
