# Generated by Django 2.0.4 on 2018-06-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0029_auto_20180601_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='stage',
            field=models.BooleanField(default=False),
        ),
    ]
