# Generated by Django 2.0.4 on 2018-06-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0030_issue_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='weekend',
            field=models.BooleanField(default=False),
        ),
    ]
