# Generated by Django 2.0.4 on 2018-06-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0031_issue_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='weekend',
        ),
    ]
