# Generated by Django 2.0.4 on 2018-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slantapp', '0032_remove_issue_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='weekend_order',
            field=models.IntegerField(default=0),
        ),
    ]
